# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tcl-pTk
version:      0.8
version_from: lib/Tcl/pTk.pm
installdirs:  site
requires:
    Tcl:                           0.9

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
